# .circleci/config.yml
version: 2.1
jobs:
  build:
    macos:
      xcode: 15.1.0
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project
      FASTLANE_LANE: ciTest
    steps:
      - checkout
      - run: bundle install
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: /Users/distiller/project
      - store_test_results:
          path: /Users/distiller/project
      # - run:
      #     name: CI Testing
      #     command: fastlane ciTest
      # - store_artifacts:
      #     path: output
      # - store_test_results:
      #     path: output/scan